output: "README.md"
embed: "."
includeUnexported: "true"
header: |+
  [![License](https://img.shields.io/github/license/nwillc/genfuncs.svg)](https://tldrlegal.com/license/-isc-license)
  [![CI](https://github.com/nwillc/genfuncs/workflows/CI/badge.svg)](https://github.com/nwillc/genfuncs/actions/workflows/CI.yml)
  [![codecov.io](https://codecov.io/github/nwillc/genfuncs/coverage.svg?branch=master)](https://codecov.io/github/nwillc/genfuncs?branch=master)
  [![Releases](https://img.shields.io/github/tag/nwillc/genfuncs.svg)](https://github.com/nwillc/genfuncs/tags)
  
  # Genfuncs
  
  Genfuncs implements various functions utilizing Go's Generics to help avoid writing boilerplate code,
  in particular when working with slices, maps and ssorting. Many of the functions are based on Kotlin's Sequence. 
  This package, though very usable, is primarily a proof-of-concept since it is likely Go will provide similar before long.
  
  Examples are found in `examples_test.go` files or projects like [gordle](https://github.com/nwillc/gordle).
  
  The code is under the [ISC License](https://github.com/nwillc/genfuncs/blob/master/LICENSE.md).
  
  # Requirements
  
  Build with Go 1.18
  
  # Getting
  
  ```bash
  go get github.com/nwillc/genfuncs
  ```
  
  # Packages
  - [genfuncs](<#genfuncs>)
  - [genfuncs/container](<#container>)

repository:
  url: https://github.com/nwillc/genfuncs
  defaultBranch: master
  path: /
